
error_log /dev/stdout info;

events {
	worker_connections 1024;
}

rtmp {
	server {
		listen 1935;
		chunk_size 4000;

		# -------------------------
		# RTMP INPUT (DJI STREAM)
		# -------------------------
		application live {
			live on;
			record off;

			# -------------------------
			# HLS ENABLED HERE
			# -------------------------
			hls on;
			hls_path /opt/data/hls;
			hls_fragment 2;
			hls_playlist_length 10;
			hls_nested on;

			# optional (better stability)
			hls_cleanup on;
		}
	}
}

http {
	server {
		listen 80;

		# -------------------------
		# HLS FILE SERVING
		# -------------------------
		location /hls {
			types {
				application/vnd.apple.mpegurl m3u8;
				video/mp2t ts;
			}

			root /opt/data;

			add_header Cache-Control no-cache;
			add_header Access-Control-Allow-Origin *;
		}

		# optional: simple health check
		location / {
			return 200 "RTMP server running\n";
		}
	}
}
